blank_issues_enabled: false
contact_links:
  - name: Submit an issue/General Questions
    url: https://bbs.luobotou.org/forum-88-1.html
    about: Please submit any issues or ask any questions at the Luobotou IT Forum.
    